server:
  port: 8080


spring:
  datasource:
    driver-class-name: ${MYSQL_DRIVER}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
#  jpa:
#    hibernate:
#      ddl-auto: create


logging:
  level:
    org:
      springframework: info
      hibernate: error
  file:
    name: logs/application.log